### ISSUE TITLE
Target Temperature shows unknown

### ISSUE THREAD

**Issue by ReconOperator** [klejejs/ha-thermia-heat-pump-integration#72]
Target Temperature shows unknown

Home Assistant Core 2023.12.1
Home Assistant Operating System 11.2
Thermia Heat Pump Integration v3.3.1
Thermia heat pump Diplomat Inverter M
Mjukvaruversion
13.0.10

My Target temperature shows state unknown in lovelace but if i click on the on the sensor (water_heater.my_sensor_name) to show the more "detailed view" it correctly shows "Current temperature 20 °C". Please see screenshots for better understanding of what i mean. 

If i search the logs for water_heater everything looks fine as far as i can see:

```
2024-01-08 20:11:00.487 INFO (SyncWorker_5) [homeassistant.loader] Loaded water_heater from homeassistant.components.water_heater

2024-01-08 20:11:00.663 INFO (MainThread) [homeassistant.setup] Setting up water_heater

2024-01-08 20:11:00.666 INFO (MainThread) [homeassistant.setup] Setup of domain water_heater took 0.0 seconds

2024-01-08 20:11:03.856 INFO (MainThread) [homeassistant.components.water_heater] Setting up water_heater.mqtt

2024-01-08 20:11:34.100 INFO (MainThread) [homeassistant.components.water_heater] Setting up water_heater.thermia

2024-01-08 20:11:00.487 INFO (SyncWorker_5) [homeassistant.loader] Loaded water_heater from homeassistant.components.water_heater
```

![thermia1](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/89938458/331d5ff7-8862-47f6-9a25-04e6befeb927)

![thermia2](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/89938458/dd2e3fe5-62bd-49e3-b2f0-cc790614ef2c)

![thermia3](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/89938458/bb3184dc-f3c3-409a-8368-91f59fa51a0c)

**Comment by klejejs** [comment]
@ReconOperator Thanks for reporting the issue! It seems there are many different heat pumps and configurations, so could you please post a screenshot of your sensor values and how they look in Thermia Online?
Are you familiar with Python? If yes, could you please follow [these instructions](https://github.com/klejejs/python-thermia-online-api#regarding-unsupported-models) and send me the debug file?

**Comment by ReconOperator** [comment]
@klejejs 

Here are some screenshots 

Regarding the Python script, where do i execute it and how do i execute it?

![t1](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/89938458/eaca5833-2a98-4078-b4f1-5fdd170197ed)
![t2](https://github.com/klejejs/ha-thermia-heat-pump-integration/assets/89938458/5edf8a6c-13be-4044-8c49-8d487b2ea99e)

**Comment by klejejs** [comment]
Can you please confirm you are not allowed to change operation, i.e., heating, auto, etc. through UI?

**Comment by klejejs** [comment]
I have just released version 4.2.0 that should fix the issue by disabling the operation mode feature if operation change is not allowed. Please check and report back if it is working now.

**Comment by ReconOperator** [comment]
Hi, just updated to 4.2.0 and now everything is unavailable 

TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'model_id'
2024-08-09 14:47:49.387 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity None for domain sensor with platform thermia
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 770, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by klejejs** [comment]
Hey @ReconOperator, are you using the latest HA version 2024.8.0? I should have added a warning about the integration needing it, will update the release notes.

**Comment by ReconOperator** [comment]
Aha, I'm still on 2024.7.4. That explain it then. Will update with info when I have had time to update HA

**Comment by ReconOperator** [comment]
@klejejs Hi, just updated to HA 2024.8.1 and Thermia Heat Pump Integration 4.2.0. I still have the same behavior as described in at the top of this issue

**Comment by jpdacostaza** [comment]
Question..? in thermia online i can not change the device modes is there a setting to change on the heatpump itself to allow these controls as im thinking the auto mode could be overiding this.. ?

![image](https://github.com/user-attachments/assets/9b000d79-f2ff-4c63-80ab-4f02fda116b3)

**Comment by klejejs** [comment]
Hey! I just released version `5.1.0`, could you please update the integration and check if the issue is still present?

**Comment by ReconOperator** [comment]
Hi @klejejs 

Great work whit the latest release 5.1.0 that fixed the issue i reported about Target Temperature so you can go ahead and close this.

![Capture](https://github.com/user-attachments/assets/cfdc0e68-fcc6-4955-a34f-c08d6db5b12b)
